MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN_ONLY: True
  YOLACT_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  RETINANET:
    SCALES_PER_OCTAVE: 3
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDES: (8, 16, 32, 64, 128)
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    NUM_CONVS: 4
    SHARE_HEAD_TOWER: False
    INFERENCE_TH: 0.05
    PRE_NMS_TOP_N: 1000
    NMS_TH: 0.5
    BBOX_REG_WEIGHT: 4.0
  YOLACT: 
    NUM_PROTOTYPES: 32
    PROTO_SRC: 0
    PROTONET: 
    - (256, 3, {'padding':1})
    - (256, 3, {'padding':1})
    - (256, 3, {'padding':1})
    - (None, -2, {})
    - (256, 3, {'padding':1})
    PROTOTYPE_ACTIVATION: "relu"
    MASK_ACTIVATION: "sigmoid"
    COEFF_ACTIVATION: "tanh"
    CONVERT_MASK_TO_RLE: True
    MASK_TO_TRAIN: 100
    USE_FAST_NMS: True
    # yolact (failed)
    # MASK_WITH_LOGITS: True
    # yolact sigmoid (failed)
    # MASK_WEIGHT: 0.01
    # MASK_WITH_LOGITS: False
    # less mask weights (failed)
    # MASK_WEIGHT: 0.1
    # MASK_WITH_LOGITS: False
    # yolact loss weight (working)
    MASK_WEIGHT: 1.0
    MASK_WITH_LOGITS: False
VISUAL:
  LOSS_KEYS:
  - loss_retina_cls
  - loss_retina_reg
  - loss_yolact_mask
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  PRESERVE_ASPECT_RATIO: True
DATALOADER:
  SIZE_DIVISIBILITY: -1
  SUBSET_SIZE: -1
TEST:
  DETECTIONS_PER_IMG: 100
  USE_YOLACT_COCO_EVAL: True
SOLVER:
  BASE_LR: 5e-4
  WEIGHT_DECAY: 5e-4
  STEPS: (560000, 720000,)
  MAX_ITER: 800000
  IMS_PER_BATCH: 4
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 10000

  # BASE_LR: 0.005
  # WEIGHT_DECAY: 0.0001
  # STEPS: (120000, 160000)
  # MAX_ITER: 180000
  # IMS_PER_BATCH: 8

  # BASE_LR: 0.02
  # WEIGHT_DECAY: 0.0001
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # IMS_PER_BATCH: 16

# OUTPUT_DIR: ./weights/debug

# yolact retinanet (working)
OUTPUT_DIR: ./weights/yolact_retinanet